In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
np.random.seed(3)
tf.random.set_seed(3)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving ThoraricSurgery.csv to ThoraricSurgery.csv


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
Data_set = np.loadtxt("/content/datasets/ThoraricSurgery.csv", delimiter=",")
Data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [ ]:
X = Data_set[:, 0:17]
Y = Data_set[:, 17]

In [ ]:
X[0]

array([293. ,   1. ,   3.8,   2.8,   0. ,   0. ,   0. ,   0. ,   0. ,
         0. ,  12. ,   0. ,   0. ,   0. ,   1. ,   0. ,  62. ])

In [ ]:
Y[0]

0.0

In [ ]:
# 딥러닝 구조를 결정합니다(모델을 설정하고 실행하는 부분입니다).
model = Sequential()
model.add(Dense(30, input_dim=17, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
# 딥러닝을 실행합니다.
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=100, batch_size=10)

Epoch 1/100
47/47 [==============================] - 1s 2ms/step - loss: 0.3551 - accuracy: 0.6362
Epoch 2/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1489 - accuracy: 0.8511
Epoch 3/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1489 - accuracy: 0.8511
Epoch 4/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1489 - accuracy: 0.8511
Epoch 5/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1489 - accuracy: 0.8511
Epoch 6/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1489 - accuracy: 0.8511
Epoch 7/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1489 - accuracy: 0.8511
Epoch 8/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1489 - accuracy: 0.8511
Epoch 9/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1489 - accuracy: 0.8511
Epoch 10/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1489 - accuracy: 0.8511
Epoch 11/

In [ ]:
#결과 확인
print('정확도 %.4f' % model.evaluate(X, Y)[1])

15/15 [==============================] - 0s 2ms/step - loss: 0.1206 - accuracy: 0.8702
정확도 0.8702


In [ ]:
new_patient_data = np.array([X[0]])
new_patient_data

array([[293. ,   1. ,   3.8,   2.8,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ,  12. ,   0. ,   0. ,   0. ,   1. ,   0. ,  62. ]])

In [ ]:
predict = model.predict(new_patient_data)
predict

1/1 [==============================] - 0s 84ms/step


array([[0.01608372]], dtype=float32)